### ISSUE TITLE
Obs for multiple IDs

### ISSUE THREAD

**Issue by msaunby** [jacobtomlinson/datapoint-js#16]
Datapoint API allows "all" and comma separated list of IDs.  Maybe add this functionality to get_obs_for_site.

Or catch the resulting error.  i.e.

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.clean_days (/Users/mike/Documents/openshift/nodejs/node_modules/datapoint-js/src/obs.js:30:33)
    at Object.module.exports.get_obs_for_site (/Users/mike/Documents/openshift/nodejs/node_modules/datapoint-js/src/obs.js:21:27)
    at Object.module.exports.get_obs_for_site (/Users/mike/Documents/openshift/nodejs/node_modules/datapoint-js/src/datapoint.js:73:16)

**Comment by jacobtomlinson** [comment]
Marking as a bug and enhancement as it is an enhancement but the error should be caught.

**Comment by jacobtomlinson** [comment]
Would this also apply to the forecast?

**Comment by msaunby** [comment]
I've not looked at forecasts so closely yet. Calling "all" on forecasts would be a bad idea though; way too much data.

**Comment by jacobtomlinson** [comment]
True
